### ISSUE TITLE
Pretraining/Finetuning XPhoneBERT on custom languages

### ISSUE THREAD

**Issue by pavanhitloop** [VinAIResearch/XPhoneBERT#21]
Hi,

I'm planning to pre-train/finetune the XPhoneBERT model for other indic languages (which do not support currently) for my research work. For this, I'm training the [CharsiuG2P](https://github.com/lingjzhu/CharsiuG2P/tree/main) with the indic languages. It would be very helpful to know if anyone has fine-tuned or pre-trained this model on custom languages. If anyone has done this before or has relevant resources, please share your insights here.

**Comment by thelinhbkhn2014** [comment]
I think you can pre-train a BERT-based model for phoneme representation for only indic languages. For converting text2phoneme, you can use another tool like phonemizer that can convert text2phoneme instead of training a new tool to do it. You can read some papers like MixPhoneBERT or MPhoneBERT, which are phoneme representation models for only English language.
